# Generated by Django 2.0 on 2018-04-23 17:09

import alted.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=48, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('volume', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('volume_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32)),
                ('volume_btc', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('day_high', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('day_low', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('highest_bid', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('lowest_ask', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('crashed', models.DateTimeField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_market_set', to='coins.Coin')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.Exchange')),
            ],
            bases=(models.Model, alted.utils.SlugifyMixin),
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('exchange', 'coin', 'base')},
        ),
    ]
