# Generated by Django 2.0 on 2018-04-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')])),
                ('price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('total', models.DecimalField(decimal_places=8, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=12)),
                ('date', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
            ],
        ),
    ]
