# Generated by Django 2.0 on 2018-04-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.DecimalField(decimal_places=8, max_digits=12)),
                ('difference_percentage', models.DecimalField(decimal_places=8, max_digits=12)),
                ('active', models.BooleanField(default=False)),
                ('buy_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitragelog_buy_market_set', to='markets.Market')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitragePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitragepair_base_set', to='coins.Coin')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitragepair_coin_set', to='coins.Coin')),
                ('markets', models.ManyToManyField(to='markets.Market')),
            ],
        ),
        migrations.CreateModel(
            name='PriceDiffPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('base_coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.Coin')),
                ('base_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricediffpair_base_market_set', to='markets.Market')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricediffpair_market_set', to='markets.Market')),
            ],
        ),
        migrations.CreateModel(
            name='PriceDiffTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=8, max_digits=12)),
                ('sell', models.DecimalField(decimal_places=8, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.PriceDiffPair')),
            ],
        ),
        migrations.AddField(
            model_name='arbitragelog',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.ArbitragePair'),
        ),
        migrations.AddField(
            model_name='arbitragelog',
            name='sell_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitragelog_sell_market_set', to='markets.Market'),
        ),
    ]
