# Generated by Django 2.0 on 2018-04-23 17:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8)),
                ('slug', models.SlugField(blank=True, max_length=8, unique=True)),
                ('volume_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True)),
                ('volume_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True)),
                ('ticker_url', models.URLField(blank=True, default='', max_length=2000)),
                ('code_substitutes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
